### ISSUE TITLE
Question about the sthv800

### ISSUE THREAD

**Issue by junny-kim** [my-smilence/my_code#2]
Hello, I am trying to use sthv800 like you have done in this repo.

One question is where did you find the information about the information about how to make the input bits to the sthv800?

I could not find any information or datasheet in the homepage of st company.

But if I see your code at sthv_800.srcs/sources_1/new/pluse_send.v

it seems that you have found how to make the bits?

I will wait for your respond! have a great day!

**Comment by my-smilence** [comment]
感谢你的来件，你的邮件殷宇昕已经收到了~

**Comment by my-smilence** [comment]
I am sending you the documentation about sthv800, I hope it will help you




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "my-smilence/sthv800_my_code"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月14日(星期三) 上午10:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[my-smilence/sthv800_my_code] Question about the sthv800 (Issue #2)





 
Hello, I am trying to use sthv800 like you have done in this repo.
 
One question is where did you find the information about the information about how to make the input bits to the sthv800?
 
I could not find any information or datasheet in the homepage of st company.
 
But if I see your code at sthv_800.srcs/sources_1/new/pluse_send.v
 
it seems that you have found how to make the bits?
 
I will wait for your respond! have a great day!

**Comment by junny-kim** [comment]
it seems that there is no file uploaded? Can you check for it?

**Comment by my-smilence** [comment]
The previous file upload failed, now all the relevant files have been uploaded and can be downloaded




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "my-smilence/sthv800_my_code"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月20日(星期二) 下午3:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [my-smilence/sthv800_my_code] Question about the sthv800 (Issue #2)





 
it seems that there is no file uploaded? Can you check for it?

**Comment by junny-kim** [comment]
thanks alot!!
